### ISSUE TITLE
no relvent codes

### ISSUE THREAD

**Issue by yeluolql** [Wangyiiiiii/Aster#1]
from target_model_data import Target_Model_pred_fn
from target_model_data import fn_R_given_Selected

**Comment by ShuchunXu** [comment]
I'm also having this issue

**Comment by Wangyiiiiii** [comment]
I have uploaded some scripts and files which are essential to run Evaluate.py.
Currently only one model and dataset are uploaded. Let me know if you need more models or datasets.
Note that you would need unzip data/mnist/mnist.zip manually before running the code.
我上传了一些运行Evaluate.py所必须的模型、数据集和脚本。
当前我只上传了一种模型和数据集，如果你需要更多的模型和数据集可以联系我。
注意在跑代码之前你需要手动解压data/mnist/mnist.zip

**Comment by yeluolql** [comment]
啊啊啊啊！ 真的非常非常感谢你的回复，我前段时间开始自己跑实验，一直在处理&nbsp;adult 数据集，后面也想在二分类数据集上做文章，可以看看在 adult 数据集跟 bank 数据集上跑实验的代码吗🫡
发自我的iPhone


------------------ Original ------------------
From: WangYi ***@***.***&gt;
Date: Fri,Oct 13,2023 9:37 AM
To: Wangyiiiiii/Aster ***@***.***&gt;
Cc: yeluolql ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Wangyiiiiii/Aster] no relvent codes (Issue #1)





 
I have uploaded some scripts and files which are essential to run Evaluate.py.
 Currently only one model and dataset are uploaded. Let me know if you need more models or datasets.
 Note that you would need unzip data/mnist/mnist.zip manually before running the code.
 我上传了一些运行Evaluate.py所必须的模型、数据集和脚本。
 当前我只上传了一种模型和数据集，如果你需要更多的模型和数据集可以联系我。
 注意在跑代码之前你需要手动解压data/mnist/mnist.zip

**Comment by Wangyiiiiii** [comment]
我现在上传了更多的模型和数据集，但由于我已毕业，有些数据不在手上也无法从实验室获取。
现在你可以修改Evaluate.py文件的第23和25行来选择你想评估的数据集和模型，那部分附有注释。（我知道让用户直接从代码里修改的方式不太友好，但这是我两年前经手的一个课题，现在不太想花精力来优化重构了。）
希望能帮助到你。

**Comment by yeluolql** [comment]
好的好的 非常感谢，祝工作学习顺利💪🏻



发自我的iPhone


------------------ Original ------------------
From: WangYi ***@***.***&gt;
Date: Fri,Oct 13,2023 3:19 PM
To: Wangyiiiiii/Aster ***@***.***&gt;
Cc: yeluolql ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Wangyiiiiii/Aster] no relvent codes (Issue #1)

**Comment by Wangyiiiiii** [comment]
不客气，也祝你实验顺利，如果有其他关于本篇论文的问题欢迎发邮件(地址在首页)讨论。
