### ISSUE TITLE
可以告知一下scikit-learn用的哪一个版本吗

### ISSUE THREAD

**Issue by yeluolql** [Wangyiiiiii/Aster#2]
Target_Model = pickle.load(f)
ModuleNotFoundError: No module named 'sklearn.linear_model.logistic'
版本不匹配在加载预训练模型的时候会报错

**Comment by Wangyiiiiii** [comment]
写论文时候的环境已经找不到了，下面是我这两天本地能跑通的版本
Python 3.7.4
numpy==1.21.2
pandas==1.3.0
scikit-learn==0.21.0
